version: '3.8'

# 此文件用于配置 Docker 网络设置
# 可以与主 docker-compose.yaml 文件一起使用：
# docker-compose -f docker-compose.yaml -f docker-compose.network.yaml up -d

services:
  worker:
    # 网络配置
    environment:
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=localhost,127.0.0.1,redis,${NO_PROXY:-}
    # DNS 配置
    dns:
      - 223.5.5.5  # 阿里 DNS
      - 114.114.114.114  # 114 DNS
    # 网络优化
    networks:
      - firecrawl-network
    # 重启策略
    restart: unless-stopped
    # 健康检查
    healthcheck:
      test: ["CMD", "pnpm", "run", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  server:
    # 网络配置
    environment:
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=localhost,127.0.0.1,redis,${NO_PROXY:-}
    # DNS 配置
    dns:
      - 223.5.5.5  # 阿里 DNS
      - 114.114.114.114  # 114 DNS
    # 网络优化
    networks:
      - firecrawl-network
    # 重启策略
    restart: unless-stopped
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    # 网络优化
    networks:
      - firecrawl-network
    # 重启策略
    restart: unless-stopped
    # 健康检查
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

# 自定义网络
networks:
  firecrawl-network:
    driver: bridge
    # 网络优化配置
    driver_opts:
      com.docker.network.driver.mtu: 1450  # 适用于 VPN 环境
    # 子网配置
    ipam:
      config:
        - subnet: 172.28.0.0/16
