version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    # 使用中国镜像源
    # image: registry.cn-hangzhou.aliyuncs.com/library/redis:latest
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: worker.china.Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
        - NO_PROXY=${NO_PROXY:-}
    image: 0001coder/coolcrawl-worker:china
    pull_policy: never
    environment:
      - REDIS_URL=redis://redis:6379
      - USE_DB_AUTHENTICATION=false
      - NODE_ENV=production
      - TZ=Asia/Shanghai
      # 网络配置
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=localhost,127.0.0.1,redis,${NO_PROXY:-}
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    # DNS 配置
    dns:
      - 223.5.5.5  # 阿里 DNS
      - 114.114.114.114  # 114 DNS
      - 8.8.8.8  # Google DNS（备用）
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  server:
    build:
      context: .
      dockerfile: server.china.Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
        - NO_PROXY=${NO_PROXY:-}
    image: 0001coder/coolcrawl-server:china
    pull_policy: never
    environment:
      - REDIS_URL=redis://redis:6379
      - USE_DB_AUTHENTICATION=false
      - HOST=0.0.0.0
      - NODE_ENV=production
      - TZ=Asia/Shanghai
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=localhost,127.0.0.1,redis,${NO_PROXY:-}
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    dns:
      - 223.5.5.5
      - 114.114.114.114
      - 8.8.8.8
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/test"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  redis_data:
    driver: local
